[font]
# Will use the bundled FiraCode Nerd Font by default.
normal = [
  # "ComicShannsMono Nerd Font",
  # "JetbrainsMono Nerd Font",
  "FiraCode Nerd Font",
  "LXGW WenKai Mono",
  "Sarasa Mono SC",
]
size = 12

fork = false
frame = "full"
idle = true
maximized = false

# # In reality found dynamically on $PATH if unset.
# neovim-bin = "/usr/bin/nvim"

no-multigrid = false
srgb = false
tabs = true
theme = "default"
title-hidden = true
vsync = true
wsl = false
