[font]
# Will use the bundled FiraCode Nerd Font by default.
normal = [
  "JetBrains Maple Mono",
  "FiraCode Nerd Font",
  "JetbrainsMono Nerd Font",
  "ComicShannsMono Nerd Font",
  "LXGW WenKai Mono",
  "Maple Mono NF CN",
  "Sarasa Mono SC",
  "Unifont",
]
size = 15

fork = false
frame = "full"
idle = true
maximized = false

# # In reality found dynamically on $PATH if unset.
# neovim-bin = "/usr/bin/nvim"

no-multigrid = false
srgb = false
tabs = true
theme = "default"
title-hidden = true
vsync = true
wsl = false
