[editor]
mouse = false
line-number = "relative"
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal."space"]
"F" = "file_picker_in_current_buffer_directory"

[keys.normal]
X = ["extend_line_up", "extend_to_line_bounds"]
A-x = "extend_to_line_bounds"

[keys.select]
X = ["extend_line_up", "extend_to_line_bounds"]
A-x = "extend_to_line_bounds"

[keys.insert]
"C-[" = "normal_mode"
"C-f" = "move_char_right"
"C-b" = "move_char_left"
"C-n" = "move_visual_line_down"
"C-p" = "move_visual_line_up"
"C-a" = "goto_line_start"
"C-e" = "goto_line_end_newline"
